#include <iostream>
#include <string>

std::string strip(std::string str);
std::string lstrip(std::string str);

int main() {
  // Flush after every std::cout / std:cerr
  std::cout << std::unitbuf;
  std::cerr << std::unitbuf;
  while (true) {
    std::cout << "$ "; // Show Prompt 

    std::string command; // Variable delaration
    std::getline(std::cin, command); //getting input from user


    // Shell Command handling
    if ( strip(command)=="exit" ) {
      break; // Exit the shell
    } else if ( lstrip(command).substr(0, 4)=="echo") {
      std::string to_echo = lstrip(command).substr(5); // Get the rest of the command after "echo"
      std::cout << to_echo << std::endl; // Print the echoed string
    } else {
      std::cout << command << ": command not found" << std::endl;
    }
  }
}

// AS A RULE FOR USING THE VSCODE AUTOCOMPLETE, I will Always note it, and
// I will research the actual content of the function generated.


/*
 * This function was generated by the VSCode Autocomplete. It should act
 * like Python's str.strip() method, removing leading and trailing whitespace.
 */
std::string strip(std::string str) { 
  // str is a copy of the passed string.
  // str::string& would be a reference to the original string and allow direct edits. 
  const char* whitespace = " \t\n\r\f\v";
  str.erase(0, str.find_first_not_of(whitespace));
  str.erase(str.find_last_not_of(whitespace) + 1);
  return str;
}


/*
 * Like strip, but only removes leading whitespace.
 */
std::string lstrip(std::string str) { 
  const char* whitespace = " \t\n\r\f\v";
  str.erase(0, str.find_first_not_of(whitespace));
  return str;
}